### ISSUE TITLE
Is it easy to change these to python?

### ISSUE THREAD

**Issue by Strive-for-excellence** [XQP-Munich/LDPC4QKD#14]
Is it easy to change these to python? I want to use distributed source coding  to compress deep learning model parameters.

**Comment by adomasbaliuka** [comment]
Are you sure the kind of LDPC matrices we are using are what you need? I looked at some publications but I'm not familiar with uses of distributed source coding for deep learning and could not easily see what requirements such applications generally have.

Other than the LDPC matrices themselves, this project does not contain any non-standard algorithms, that (I would expect) you could not get elsewhere with Python bindings available. The encoder provided here is trivial (sparse matrix-vector multiplication) and the decoder is a standard implementation of belief propagation decoding.
